apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-module-9790
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/service-module-9790
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
